### PR TITLE
README.md - Suggest -vcs option with 'gohack get' as having vcs is th…

### PR DESCRIPTION
**Pull request by chmorgan**
…e likely desired behavior

### CODE REVIEW

**Comment by davidovich** [comment]
In fact, `-vcs` is an additional mode to the base use case which does not initialize a repo (if you want to make a fast one-off non tracked modification). We would need to state that in addition to the non `-vcs` case.

**Comment by chmorgan** [comment]
I ran without -vcs and ended up without a .git, ran with -vcs and it had a .git as expected. Maybe the logic was unintentionally reversed? Imo the default should be to have a git repo to work with so it didn’t make sense to me initially.

**Comment by chmorgan** [comment]
I can expand upon the two cases and why you might use one over the other. Imo it was counterintuitive that I didn’t get a vcs by default. Maybe we should reverse the logic on the option, make it -novcs? Disk space and bandwidth would be increased but these days it’s not a big deal for most people.

**Comment by davidovich** [comment]
I think changing the default should be proposed in a new issue so that maintainers can get a shot at discussing it. There must be a reason for the current (non-vcs) default.

**Comment by chmorgan** [comment]
Agreed. Let me fix this pr up tonight and open a separate one to swap the defaults.

**Comment by chmorgan** [comment]
Hi @davidovich alright, ready for re-review. I took the liberty of using some markdown to break things into easier to follow sections as well.

**Comment by davidovich** [comment]
@chmorgan I do not have merge privileges, but I think your changes are a great documentation addition. We just merged one of my changes that enhances setting GOHACK to a relative directory to control where the module lands. Want to document that also ? :-) (GOHACK en var was not documented before).

**Comment by chmorgan** [comment]
HI @davidovich. I could take a swag at updating that once this one is merged in. I'd rather not stack anything up behind it in case people prefer the flat unformatted look and the edits are rejected :-) But I can take a quick look once this is in. Should only take a few minutes to document that but as the original author you may be the person that knows it best ;-)

**Comment by davidovich** [comment]
You're right, I won't be lazy :-). I'll wait till the maintainers see if this change is acceptable, and make the GOHACK doc update PR on top.

**Comment by chmorgan** [comment]
Any updates on this PR?

**Comment by myitcv** [comment]
cc @rogpeppe

**Comment by chmorgan** [comment]
and on this one?

**Pull request merged**
